

// This File is AUTO-GENERATED by ConstantsBuilder.exe!!
// Do not change this file manually, otherwise changes may get lost if ConstantsBuilder
// regenerate the File.
// If you need to change values please look at the Json Build Document "Constants.json"!
//
// File "Constants1.cs" was last updated on Tue, 16 Mar 2021 20:39:16 GMT


public struct Constants
{


#if MyCondition

	public struct SubConstants
	{
		public const string constant1 = "constant1";
		public const string constant2 = "Value";

		public struct SubsubConstants
		{

#if MyPreprocessorCondition

			public const string constant1 = "constant1";

#endif


			public struct SubSubSubConstants
			{
				public const string myConstant = "myConstant";

			}
		}
	}

#endif

}
